name: Update README

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch: # Allows manual run

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update README with current time
      run: |
        echo "Last Updated on $(date)" > last-updated.txt
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add last-updated.txt
        git commit -m "chore: auto-update README timestamp"
        git push
